#!/bin/sh

$HOME/.config/polybar/launch.sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5

bspc config border_width       2
bspc config window_gap         10
bspc config single_monocle     true
bspc config borderless_monocle true
bspc config gapless_monocle    true

bspc rule -a Chromium desktop='^2'
bspc rule -a discord  desktop='^3'

. "$HOME/.config/daub/gen/colors.sh"
bspc config normal_border_color   "$lv02"
bspc config active_border_color   "$clbl"
bspc config focused_border_color  "$clbl"
bspc config presel_feedback_color "$lv01"
